### ISSUE TITLE
Output size error

### ISSUE THREAD

**Issue by shqing** [TAMU-VITA/Orthogonality-in-CNNs#5]
Hi, when I run the SVHN/train.py, there is an error:  
/usr/bin/python3.6 /home/zm/Can-we-Gain-More-from-Orthogonality-master/SVHN/train.py
Namespace(batch_size=50, cuda=False, data_augmentation=False, dataset='cifar10', epochs=200, learning_rate=0.1, length=16, model='resnet18', n_holes=1, no_cuda=True, ortho_decay=0.01, seed=0)
Files already downloaded and verified
Files already downloaded and verified
Epoch 0:   0%|          | 0/1000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/zm/Can-we-Gain-More-from-Orthogonality-master/SVHN/train.py", line 263, in <module>
    pred = cnn(images)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zm/Can-we-Gain-More-from-Orthogonality-master/SVHN/model/resnet.py", line 146, in forward
    x = self.avgpool(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/pooling.py", line 565, in forward
    self.padding, self.ceil_mode, self.count_include_pad)
RuntimeError: Given input size: (512x1x1). Calculated output size: (512x-5x-5). Output size is too small at /pytorch/aten/src/THNN/generic/SpatialAveragePooling.c:48

How to fix this error ?

**Comment by nbansal90** [comment]
Hi shqing!

At what stage are you getting this error?
Have you made sure, if the Image size is correct ?(Image Size for SVHN is 32 x 32)?

Nitin

**Comment by shqing** [comment]
Hi Nitin:
    Yes, the Image size is 32 x 32, when I comment out  the line x = self.avgpool(x), the error  disappear.

shqing
